name: ğŸ” Cypress E2E Tests

on:
  push:
    branches: Master
  pull_request:
    branches: Master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ§ª Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      #- name: ğŸ“ Cache npm
       # uses: actions/cache@v3
       # with:
       #   path: ~/.npm
        #  key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        #  restore-keys: |
        #    npm-cache-${{ runner.os }}-

      #- name: ğŸ“ Cache Cypress binary
     #   uses: actions/cache@v3
     #   with:
      #    path: ~/.cache/Cypress
      #    key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
       #   restore-keys: |
        #    cypress-cache-${{ runner.os }}-
            
      - name: ğŸ”¥ Fully clean node_modules and .cache
        run: |
          sudo rm -rf node_modules frontend/node_modules frontend/node_modules/.cache

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ”¨ Start frontend app
        run: npm start &
        env:
          NODE_ENV: development

      - name: ğŸ§« Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          config-file: cypress.config.js
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          cache: false  


